source 'https://rubygems.org'

gem "sinatra"
gem "erubis"
gem "rack-livereload", :group => :development
gem "activerecord"
gem "sqlite3"

group :development do
  gem "guard"
  gem "guard-rack"
  gem "guard-bundler", require: false
end
